Fix tag clean release candidate

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -106,7 +106,7 @@ jobs:
           if [[ -n "$RC_TAGS" ]]; then
             for rc_tag in $RC_TAGS; do
               echo "Deleting remote tag $rc_tag"
-              git push --delete "$rc_tag" || echo "::warning::Failed to delete tag $rc_tag. It might have already been deleted."
+              git push --delete origin "$rc_tag" || echo "::warning::Failed to delete tag $rc_tag. It might have already been deleted."
             done
           else
             echo "No RC tags found to delete."
